# Generated by Django 4.1.7 on 2023-02-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.weatherstation')),
            ],
            options={
                'unique_together': {('date', 'station')},
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_max_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_min_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_precipitation', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.weatherstation')),
            ],
            options={
                'unique_together': {('year', 'station')},
            },
        ),
    ]
