# Generated by Django 4.1.7 on 2023-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='station_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
