# Generated by Django 4.1.7 on 2023-02-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_alter_weatherdata_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='station',
            field=models.IntegerField(),
        ),
    ]
