# Generated by Django 4.1.7 on 2023-02-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_alter_statistics_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='station',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='weather_app.weatherdata'),
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
